### ISSUE TITLE
Problem parsing the earthquake JSON results

### ISSUE THREAD

**Issue by s0ullight** [udacity/ud843_Soonami#2]
The code in current state produces the error below.
This happens because the URL redirects to an https page.
Thus the server response is an HTML page instead of a JSON object.
I've fixed the issue in my fork of the code and created a pull request.

E/MainActivity: Problem parsing the earthquake JSON results
                org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
                    at org.json.JSON.typeMismatch(JSON.java:111)
                    at org.json.JSONObject.<init>(JSONObject.java:160)
                    at org.json.JSONObject.<init>(JSONObject.java:173)
                    at com.example.android.soonami.MainActivity$TsunamiAsyncTask.extractFeatureFromJson(MainActivity.java:205)
                    at com.example.android.soonami.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:119)
                    at com.example.android.soonami.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:103)
                    at android.os.AsyncTask$2.call(AsyncTask.java:304)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                    at java.lang.Thread.run(Thread.java:761)

**Comment by TinaT2** [comment]
In Log.v says that "301 Moved Permanently".
I've found solution. The USGS_REQUEST_URL should be like this: "https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2012-01-01&endtime=2012-12-01&minmagnitude=6"
It contains "s" in https instead of http.
I tried it and it worked.

**Comment by wenzhifeifeidetutu** [comment]
The URl is should be this:
"https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2012-01-01&endtime=2012-12-01&minmagnitude=6"
_____________________________________________________________________
https is not http and it will be works now

**Comment by ntnlabs** [comment]
I edited the source and solution to reflect this change.

**Comment by MikeVelazcoMtz** [comment]
Just replace the protocol http to https.

**Comment by benkwee** [comment]
Here's the update needed to address this error.
https://github.com/benkwee/ud843_Soonami/commit/03baa96706db4875557d3f61af62b490eb08aba5

**Comment by ordago** [comment]
@cdlei

Please, fix this

**Comment by jlin27** [comment]
Thanks for finding the issue! Code is corrected now.

**Comment by Saurabh-Thakur-07** [comment]
> The code in current state produces the error below.
> This happens because the URL redirects to an https page.
> Thus the server response is an HTML page instead of a JSON object.
> I've fixed the issue in my fork of the code and created a pull request.
> 
> E/MainActivity: Problem parsing the earthquake JSON results
> org.json.JSONException: Value (JSONObject.java:160)
> at org.json.JSONObject.(JSONObject.java:173)
> at com.example.android.soonami.MainActivity$TsunamiAsyncTask.extractFeatureFromJson(MainActivity.java:205)
> at com.example.android.soonami.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:119)
> at com.example.android.soonami.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:103)
> at android.os.AsyncTask$2.call(AsyncTask.java:304)
> at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)

E/MainActivity: Problem parsing the earthquake JSON results
    org.json.JSONException: End of input at character 0 of 
        at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
        at org.json.JSONTokener.nextValue(JSONTokener.java:101)
        at org.json.JSONObject.<init>(JSONObject.java:164)
        at org.json.JSONObject.<init>(JSONObject.java:181)
        at com.example.tsunamiapp.MainActivity$TsunamiAsyncTask.extractFeatureFromJson(MainActivity.java:119)
        at com.example.tsunamiapp.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:60)
        at com.example.tsunamiapp.MainActivity$TsunamiAsyncTask.doInBackground(MainActivity.java:43)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)


After even changing the url I m still getting this error
